apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_ENV: "production"
  APP_VERSION: "1.1"
  APP_COLOR: "green"
  DB_HOST: "postgres.default.svc.cluster.remote"
  DB_PORT: "123456789"
  DB_NAME: "mongo-db"
  FEATURE_FLAGS: "dark-mode,new-dashboard"
