apiVersion: v1
kind: Service
metadata:
  name: envapp
spec:
  type: NodePort
  selector:
    app: envapp
  ports:
  - port: 80           # cluster-internal port
    targetPort: 8080   # container port (must match containerPort)
    nodePort: 30080  